In [89]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [90]:
df=pd.read_csv('insurance.csv')
df.head()

,age,sex,bmi,children,smoker,region,charges
0,19,female,27.900,0,yes,southwest,16884.92400
1,18,male,33.770,1,no,southeast,1725.55230
2,28,male,33.000,3,no,southeast,4449.46200
3,33,male,22.705,0,no,northwest,21984.47061
4,32,male,28.880,0,no,northwest,3866.85520


In [91]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1338 entries, 0 to 1337
Data columns (total 7 columns):
 #   Column    Non-Null Count  Dtype  
---  ------    --------------  -----  
 0   age       1338 non-null   int64  
 1   sex       1338 non-null   object 
 2   bmi       1338 non-null   float64
 3   children  1338 non-null   int64  
 4   smoker    1338 non-null   object 
 5   region    1338 non-null   object 
 6   charges   1338 non-null   float64
dtypes: float64(2), int64(2), object(3)
memory usage: 73.3+ KB


In [92]:
df.isnull().sum()

,0
age,0
sex,0
bmi,0
children,0
smoker,0
region,0
charges,0


***Features aur Target alag karo***

In [93]:
X=df.iloc[:,:-1].values
y=df.iloc[:,-1].values

In [94]:
print(X)

[[19 'female' 27.9 0 'yes' 'southwest']
 [18 'male' 33.77 1 'no' 'southeast']
 [28 'male' 33.0 3 'no' 'southeast']
 ...
 [18 'female' 36.85 0 'no' 'southeast']
 [21 'female' 25.8 0 'no' 'southwest']
 [61 'female' 29.07 0 'yes' 'northwest']]


In [95]:
print(y)

[16884.924   1725.5523  4449.462  ...  1629.8335  2007.945  29141.3603]


***Encoding variables***

In [96]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder,LabelEncoder

le1=LabelEncoder()
le2=LabelEncoder()
X[:,1]=le1.fit_transform(X[:,1])
X[:,4]=le2.fit_transform(X[:,4])

ct=ColumnTransformer(transformers=[('encoder',OneHotEncoder(drop='first'),[5])],remainder='passthrough')
X=np.array(ct.fit_transform(X))

In [97]:
print(X)

[[0.0 0.0 1.0 ... 27.9 0 1]
 [0.0 1.0 0.0 ... 33.77 1 0]
 [0.0 1.0 0.0 ... 33.0 3 0]
 ...
 [0.0 1.0 0.0 ... 36.85 0 0]
 [0.0 0.0 1.0 ... 25.8 0 0]
 [1.0 0.0 0.0 ... 29.07 0 1]]


***Train-Test Split***

In [98]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.25,random_state=0)

In [99]:
y_train.shape

(1003,)

In [100]:
X_train.shape

(1003, 8)

In [101]:
y_test.shape

(335,)

***Feature Scaling***

In [102]:
from sklearn.preprocessing import StandardScaler
ss=StandardScaler()
X_train[:, [4, 6]] = ss.fit_transform(X_train[:, [4, 6]])
X_test[:, [4, 6]] = ss.transform(X_test[:, [4, 6]])

print(X_train)

[[0.0 1.0 0.0 ... 29.59 -0.06360656793383669 0]
 [0.0 0.0 0.0 ... 22.04 -0.892144069721345 0]
 [0.0 0.0 1.0 ... 24.6 -0.06360656793383669 0]
 ...
 [0.0 1.0 0.0 ... 25.08 -0.892144069721345 0]
 [1.0 0.0 0.0 ... 35.53 -0.892144069721345 0]
 [0.0 0.0 1.0 ... 18.5 -0.06360656793383669 0]]


In [104]:
from sklearn.linear_model import LinearRegression
regressor=LinearRegression()
regressor.fit(X_train,y_train)

LinearRegression()

In [113]:
y_pred = regressor.predict(X_test)
np.set_printoptions(precision=2)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

[[1.11e+04 9.72e+03]
 [9.37e+03 8.55e+03]
 [3.83e+04 4.57e+04]
 [1.63e+04 1.30e+04]
 [7.04e+03 9.64e+03]
 [4.10e+03 4.50e+03]
 [1.73e+03 2.20e+03]
 [1.45e+04 1.14e+04]
 [9.17e+03 7.54e+03]
 [7.72e+03 5.43e+03]
 [4.63e+03 6.75e+03]
 [1.04e+04 1.05e+04]
 [8.76e+03 7.34e+03]
 [3.74e+03 4.19e+03]
 [2.82e+04 1.83e+04]
 [1.06e+04 1.07e+04]
 [1.14e+04 1.25e+04]
 [6.25e+03 3.49e+03]
 [8.42e+03 6.46e+03]
 [2.74e+04 3.35e+04]
 [3.38e+04 2.40e+04]
 [1.44e+04 1.26e+04]
 [1.18e+04 2.30e+04]
 [3.21e+04 2.31e+04]
 [4.15e+03 1.67e+03]
 [9.36e+03 4.67e+03]
 [1.23e+03 3.73e+03]
 [9.71e+03 7.68e+03]
 [3.71e+03 3.76e+03]
 [1.06e+04 8.41e+03]
 [9.16e+03 8.06e+03]
 [4.00e+04 4.90e+04]
 [1.56e+04 1.30e+04]
 [1.38e+04 2.06e+04]
 [2.50e+04 1.46e+04]
 [5.27e+03 4.14e+03]
 [1.25e+04 8.35e+03]
 [3.08e+04 5.12e+04]
 [3.37e+04 4.00e+04]
 [3.69e+03 1.88e+03]
 [4.08e+03 5.46e+03]
 [3.96e+03 2.87e+03]
 [3.07e+04 2.01e+04]
 [3.96e+04 4.75e+04]
 [2.78e+04 3.61e+04]
 [5.30e+03 2.60e+04]
 [1.05e+04 1.97e+04]
 [8.00e+03 6.

In [140]:
from sklearn.metrics import r2_score,mean_squared_error

print(r2_score(y_test, y_pred))
print(np.sqrt(mean_squared_error(y_test, y_pred)))

0.7958786376014414
5668.8400259119835


***Polynomial Regression***

In [116]:
from sklearn.preprocessing import PolynomialFeatures
poly_reg = PolynomialFeatures(degree = 4)
X_train_poly = poly_reg.fit_transform(X_train)
X_test_poly = poly_reg.fit_transform(X_test)
lin_reg_2 = LinearRegression()
lin_reg_2.fit(X_train_poly, y_train)

LinearRegression()

In [128]:
y_pred_poly=lin_reg_2.predict(X_test_poly)
np.set_printoptions(precision=2)
print(np.concatenate((y_pred_poly.reshape(len(y_pred_poly),1), y_test.reshape(len(y_test),1)),1))

[[ 1.15e+04  9.72e+03]
 [ 9.43e+03  8.55e+03]
 [ 6.76e+04  4.57e+04]
 [ 9.15e+03  1.30e+04]
 [ 1.66e+04  9.64e+03]
 [ 3.71e+03  4.50e+03]
 [ 3.01e+03  2.20e+03]
 [ 1.26e+04  1.14e+04]
 [ 8.62e+03  7.54e+03]
 [ 9.25e+03  5.43e+03]
 [ 6.19e+03  6.75e+03]
 [ 1.16e+04  1.05e+04]
 [ 8.46e+03  7.34e+03]
 [ 1.00e+04  4.19e+03]
 [ 2.00e+04  1.83e+04]
 [ 1.45e+04  1.07e+04]
 [ 1.33e+04  1.25e+04]
 [ 8.69e+03  3.49e+03]
 [ 8.12e+03  6.46e+03]
 [ 2.80e+04  3.35e+04]
 [ 2.34e+04  2.40e+04]
 [ 1.63e+04  1.26e+04]
 [ 1.14e+04  2.30e+04]
 [ 3.02e+04  2.31e+04]
 [ 3.34e+03  1.67e+03]
 [ 1.01e+04  4.67e+03]
 [ 7.84e+03  3.73e+03]
 [ 1.08e+04  7.68e+03]
 [ 8.25e+03  3.76e+03]
 [ 1.08e+04  8.41e+03]
 [ 8.20e+03  8.06e+03]
 [ 4.75e+04  4.90e+04]
 [ 1.32e+04  1.30e+04]
 [ 1.13e+04  2.06e+04]
 [ 1.18e+04  1.46e+04]
 [ 5.12e+03  4.14e+03]
 [ 9.26e+03  8.35e+03]
 [ 3.99e+04  5.12e+04]
 [ 4.16e+04  4.00e+04]
 [ 3.49e+03  1.88e+03]
 [ 7.80e+03  5.46e+03]
 [ 3.47e+03  2.87e+03]
 [ 2.80e+04  2.01e+04]
 [ 5.94e+04

In [139]:
print(r2_score(y_test, y_pred_poly))
print(np.sqrt(mean_squared_error(y_test, y_pred_poly)))

0.7939681652666519
5695.306973342998


**SVR**

In [122]:
from sklearn.svm import SVR
regressor_SVR = SVR(kernel = 'rbf')
regressor_SVR.fit(X_train, y_train)

SVR()

In [123]:
y_pred_SVR=regressor_SVR.predict(X_test)
np.set_printoptions(precision=2)
print(np.concatenate((y_pred_SVR.reshape(len(y_pred_SVR),1), y_test.reshape(len(y_test),1)),1))

[[ 9497.97  9724.53]
 [ 9470.8   8547.69]
 [ 9479.71 45702.02]
 [ 9537.72 12950.07]
 [ 9484.95  9644.25]
 [ 9397.29  4500.34]
 [ 9338.81  2198.19]
 [ 9494.58 11436.74]
 [ 9420.49  7537.16]
 [ 9384.81  5425.02]
 [ 9397.53  6753.04]
 [ 9485.56 10493.95]
 [ 9448.43  7337.75]
 [ 9392.45  4185.1 ]
 [ 9366.51 18310.74]
 [ 9486.57 10702.64]
 [ 9529.98 12523.6 ]
 [ 9363.99  3490.55]
 [ 9420.1   6457.84]
 [ 9344.32 33475.82]
 [ 9490.1  23967.38]
 [ 9518.26 12643.38]
 [ 9498.21 23045.57]
 [ 9470.22 23065.42]
 [ 9351.24  1674.63]
 [ 9393.23  4667.61]
 [ 9371.92  3732.63]
 [ 9432.87  7682.67]
 [ 9383.06  3756.62]
 [ 9460.12  8413.46]
 [ 9431.    8059.68]
 [ 9529.75 48970.25]
 [ 9541.27 12979.36]
 [ 9513.99 20630.28]
 [ 9356.37 14571.89]
 [ 9378.88  4137.52]
 [ 9468.43  8347.16]
 [ 9374.81 51194.56]
 [ 9432.9  40003.33]
 [ 9345.4   1880.49]
 [ 9407.24  5458.05]
 [ 9374.51  2867.12]
 [ 9424.71 20149.32]
 [ 9527.01 47496.49]
 [ 9343.87 36149.48]
 [ 9347.71 26018.95]
 [ 9486.4  19749.38]
 [ 9441.31  6

In [138]:
print(r2_score(y_test, y_pred_SVR))
print(np.sqrt(mean_squared_error(y_test, y_pred_SVR)))

-0.09775588810693181
13146.279451129414


**Desicion Tree**

In [125]:
from sklearn.tree import DecisionTreeRegressor
regressor_DT = DecisionTreeRegressor(random_state = 0)
regressor_DT.fit(X_train, y_train)

DecisionTreeRegressor(random_state=0)

In [126]:
y_pred_DT=regressor_DT.predict(X_test)
np.set_printoptions(precision=2)
print(np.concatenate((y_pred_DT.reshape(len(y_pred_DT),1), y_test.reshape(len(y_test),1)),1))

[[ 9748.91  9724.53]
 [ 8233.1   8547.69]
 [44202.65 45702.02]
 [12741.17 12950.07]
 [ 9855.13  9644.25]
 [21984.47  4500.34]
 [ 2200.83  2198.19]
 [10600.55 11436.74]
 [ 7281.51  7537.16]
 [ 6128.8   5425.02]
 [ 4766.02  6753.04]
 [30284.64 10493.95]
 [ 6849.03  7337.75]
 [ 4779.6   4185.1 ]
 [35147.53 18310.74]
 [ 8233.1  10702.64]
 [12323.94 12523.6 ]
 [ 3292.53  3490.55]
 [ 6455.86  6457.84]
 [33907.55 33475.82]
 [24667.42 23967.38]
 [12495.29 12643.38]
 [ 9625.92 23045.57]
 [24915.22 23065.42]
 [ 1391.53  1674.63]
 [ 4462.72  4667.61]
 [ 3558.62  3732.63]
 [ 6185.32  7682.67]
 [ 3736.46  3756.62]
 [ 7731.86  8413.46]
 [ 7201.7   8059.68]
 [48673.56 48970.25]
 [13462.52 12979.36]
 [ 9850.43 20630.28]
 [15359.1  14571.89]
 [ 3866.86  4137.52]
 [ 8978.19  8347.16]
 [36219.41 51194.56]
 [39983.43 40003.33]
 [ 1391.53  1880.49]
 [21984.47  5458.05]
 [ 3972.92  2867.12]
 [21082.16 20149.32]
 [49577.66 47496.49]
 [37133.9  36149.48]
 [ 3579.83 26018.95]
 [ 8232.64 19749.38]
 [ 6358.78  6

In [137]:
print(r2_score(y_test, y_pred_DT))
print(np.sqrt(mean_squared_error(y_test, y_pred_DT)))

0.7103358863330081
6753.008855917468


***Random Forest***

In [130]:
from sklearn.ensemble import RandomForestRegressor
regressor_RF = RandomForestRegressor(n_estimators = 150, random_state = 0)
regressor_RF.fit(X_train, y_train)

RandomForestRegressor(n_estimators=150, random_state=0)

In [131]:
y_pred_RF=regressor_RF.predict(X_test)
np.set_printoptions(precision=2)
print(np.concatenate((y_pred_RF.reshape(len(y_pred_RF),1), y_test.reshape(len(y_test),1)),1))

[[10444.35  9724.53]
 [ 9663.66  8547.69]
 [45675.59 45702.02]
 [13192.89 12950.07]
 [ 9501.53  9644.25]
 [11134.24  4500.34]
 [ 2045.5   2198.19]
 [13486.39 11436.74]
 [ 7261.03  7537.16]
 [ 6881.51  5425.02]
 [ 7458.38  6753.04]
 [19079.41 10493.95]
 [ 9509.11  7337.75]
 [ 6957.89  4185.1 ]
 [25761.63 18310.74]
 [14616.85 10702.64]
 [13313.02 12523.6 ]
 [ 3878.74  3490.55]
 [ 6736.37  6457.84]
 [34033.74 33475.82]
 [24010.98 23967.38]
 [16476.94 12643.38]
 [10586.17 23045.57]
 [27173.88 23065.42]
 [ 2237.62  1674.63]
 [ 5630.78  4667.61]
 [ 6680.04  3732.63]
 [ 8934.39  7682.67]
 [ 3882.31  3756.62]
 [11421.78  8413.46]
 [ 7746.1   8059.68]
 [48365.07 48970.25]
 [14167.25 12979.36]
 [10891.75 20630.28]
 [16464.66 14571.89]
 [ 4558.14  4137.52]
 [ 9354.4   8347.16]
 [37806.89 51194.56]
 [40069.48 40003.33]
 [ 4946.37  1880.49]
 [ 9150.54  5458.05]
 [ 3992.71  2867.12]
 [20783.94 20149.32]
 [47555.2  47496.49]
 [37104.67 36149.48]
 [ 5840.9  26018.95]
 [14600.92 19749.38]
 [ 6728.97  6

In [136]:
print(r2_score(y_test, y_pred_RF))
rmse=mean_squared_error(y_test, y_pred_RF)
print(np.sqrt(rmse))

0.8746818555383231
4441.779037407534
